# Generated by Django 3.1.7 on 2021-03-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('pcp', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=250)),
            ],
        ),
    ]
