# Generated by Django 3.1.7 on 2021-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_child_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_activity',
            name='time',
            field=models.CharField(default='17:30:44', max_length=9),
        ),
    ]
