# Generated by Django 3.1.7 on 2021-04-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_daily_activity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_activity',
            name='time',
            field=models.CharField(default='19:57:12', max_length=9),
        ),
    ]
