# Generated by Django 3.1.7 on 2021-04-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210402_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_image',
            field=models.ImageField(default=1, upload_to='img/%y'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daily_activity',
            name='time',
            field=models.CharField(default='22:36:53', max_length=9),
        ),
    ]
