# Generated by Django 3.1.7 on 2021-04-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210402_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_image',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='daily_activity',
            name='time',
            field=models.CharField(default='00:22:07', max_length=9),
        ),
    ]
