# Generated by Django 3.1.7 on 2021-04-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210404_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_image',
            field=models.ImageField(default=1, upload_to='child/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daily_activity',
            name='time',
            field=models.CharField(default='19:06:03', max_length=9),
        ),
    ]
