# Generated by Django 3.1.7 on 2021-04-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20210404_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_activity',
            name='time',
            field=models.CharField(default='21:01:22', max_length=9),
        ),
    ]
